version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # localstack enpoint

    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - ./localstack-script:/etc/localstack/init/ready.d
